version: '3'

services:
  app:
    build: .
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - '8888:8888'
    volumes:
      - ..:/work/
    command: /bin/sh -c "while sleep 1000; do :; done"